services:
  - type: web
    name: weathertgbot
    env: python
    runtime: python
    pythonVersion: 3.10.12
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python tg_bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEATHER_API_KEY
        sync: false
