services:
  - type: web
    name: telegram-weather-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python tg_bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: WEATHER_API_KEY
        sync: false
